apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-project
  namespace: argocd
spec:
  description: Proyecto para el microservicio example-project
  sourceRepos:
    - 'https://github.com/Neniel/poc-infra.git'
  destinations:
    - namespace: 'example-project-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
