apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-rest-api-manual-sync
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Neniel/poc-infra.git'
        revision: HEAD
        directories:
          - path: 'argocd/apps/poc-rest-api/overlays/prod'
  template:
    metadata:
      name: 'poc-rest-api-{{path.basename}}'
      labels:
        scope: app
        app: poc-rest-api
        environment: '{{path.basename}}'
    spec:
      project: example-project
      source:
        repoURL: 'https://github.com/Neniel/poc-infra.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'poc-rest-api-{{path.basename}}'
