apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-rest-api
  namespace: argocd
spec:
  generators:
    # El generador 'merge' sigue siendo la estrategia correcta.
    - merge:
        mergeKeys:
          - path.basename
        generators:
          # 1. Generador Git: Descubre todos los directorios/entornos.
          - git:
              repoURL: 'https://github.com/Neniel/poc-infra.git'
              revision: HEAD
              directories:
                - path: 'apps/poc-rest-api/overlays/*'
          # 2. Generador List: Define los valores que se deben aplicar a 'dev'.
          - list:
              elements:
                - path.basename: dev
                  # En lugar de un objeto completo, pasamos los valores individuales.
                  isDev: true
  template:
    metadata:
      name: 'poc-rest-api-{{path.basename}}'
      labels:
        app: poc-rest-api
        environment: '{{path.basename}}'
    spec:
      project: example-project
      source:
        repoURL: 'https://github.com/Neniel/poc-infra.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'poc-rest-api-{{path.basename}}'

      # CORRECCIÓN: El bloque syncPolicy siempre existe, pero sus valores son condicionales.
      # Esto asegura que el YAML siempre sea sintácticamente válido.
      syncPolicy:
        automated:
          # Si 'isDev' es true (solo para dev), usa 'true'. Si no, usa el valor por defecto 'false'.
          prune: false
          selfHeal: false
