apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-rest-api-auto-sync
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Neniel/poc-infra.git'
        revision: HEAD
        directories:
          - path: 'apps/poc-rest-api/overlays/dev'
  template:
    metadata:
      name: 'poc-rest-api-dev'
      labels:
        app: poc-rest-api
        environment: 'dev'
    spec:
      project: example-project
      source:
        repoURL: 'https://github.com/Neniel/poc-infra.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'poc-rest-api-dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
